apiVersion: apps/v1
kind: Deployment
metadata:
  name: skiapp-deployment
  namespace: team-riker
spec:
  selector:
    matchLabels:
      app: skiapp
  replicas: 2
  #replicas: 3 # <- change replicas to 3 for testing Karpenter
  template:
    metadata:
      labels:
        app: skiapp
    spec:
      containers:
        - name: skiapp
          image: sharepointoscar/skiapp:v2
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      #nodeSelector: # <- add nodeSelector, toleration and spread constraints
      #  team: default
      #  type: karpenter
      #tolerations:
      #  - key: "karpenter"
      #    operator: "Exists"
      #    effect: "NoSchedule"
      #topologySpreadConstraints:
      #  - maxSkew: 1
      #    topologyKey: topology.kubernetes.io/zone
      #    whenUnsatisfiable: DoNotSchedule
      #    labelSelector:
      #      matchLabels:
      #        app: skiapp
